image: aemdesign/centos-java-buildpack:latest

pipelines:
  default:
    - step:
        name: package
        caches:
          - maven # adds docker layer caching
          - node
        script:
          - echo $PATH
          - ls -latr /apps/maven/bin
          - export PATH=/apps/maven/bin:${PATH}
          - export PATH=/usr/lib/node_modules/yarn/bin:${PATH}
          - echo $PATH
          - which mvn
          - which yarn
          - which node
          - mvn -version
          - yarn --version
          - npm --version
  branches:
    master:
      - step:
          name: package
          caches:
            - maven # adds docker layer caching
            - node
          script:
            - git lfs install
            - git checkout master
            - git reset --hard "origin/master"
            - git submodule sync
            - git submodule update --remote --init && echo "OK - git submodule update --remote --init"
            - mvn clean package -DskipTests=true -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  #          - git config --global user.email "$email"
  #          - git config --global user.name "$name
  #          - mvn -batch-mode release:prepare -Dusername=$USERNAME -Dpassword=$PASSWORD -DscmCommentPrefix="[skip ci]"
  #          - mvn release:perform -Dgoals=install
          artifacts:
            - swinburne-aem-deploy/target/*.zip
            - swinburne-testing/target/**
    develop:
      - step:
          name: package
          caches:
            - maven # adds docker layer caching
            - node
          script:
            - git lfs install
            - git checkout develop
            - git reset --hard "origin/develop"
            - git submodule sync
            - git submodule update --remote --init && echo "OK - git submodule update --remote --init"
            - mvn clean package -DskipTests=true -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  #          - git config --global user.email "$email"
  #          - git config --global user.name "$name
  #          - mvn -batch-mode release:prepare -Dusername=$USERNAME -Dpassword=$PASSWORD -DscmCommentPrefix="[skip ci]"
  #          - mvn release:perform -Dgoals=install
          artifacts:
            - swinburne-aem-deploy/target/*.zip
            - swinburne-testing/target/**
      - step:
          name: install to dev
          trigger: manual
          deployment: test
          script:
#            - git lfs install
#            - git checkout develop
#            - git reset --hard "origin/develop"
#            - git submodule sync
#            - git submodule update --remote --init && echo "OK - git submodule update --remote --init"
            - mvn clean install -Dcrx.host=$DEV_AUTHOR_HOST -Dcrx.port=$DEV_AUTHOR_PORT -Dcrx.username=$DEV_AUTHOR_USER -Dcrx.password=$DEV_AUTHOR_USER_PASSWORD -e -U -P deploymentpackage,installdeploymentpackage -DskipTests=true -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn


definitions:
  services:
    docker:
      memory: 2048