image: aemdesign/centos-java-buildpack:latest

pipelines:
  default:
    - step:
        name: package
        trigger: manual
        services:
          - maven
        caches:
          - maven # adds docker layer caching
          - node
        script:
          - echo $PATH
          - ls -latr /apps/maven/bin
          - export PATH=/apps/maven/bin:${PATH}
          - export PATH=/usr/lib/node_modules/yarn/bin:${PATH}
          - echo $PATH
          - which mvn
          - which yarn
          - which node
          - mvn -version
          - yarn --version
          - npm --version
          - git lfs install
          - git checkout master
          - git reset --hard "origin/master"
          - git submodule sync
          - git submodule update --remote --init && echo "OK - git submodule update --remote --init"
          - mvn clean package -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        artifacts:
          - *-deploy/target/*.zip
          - *-testing/target/**/*

definitions:
  services:
    docker:
      memory: 2048