image: aemdesign/centos-java-buildpack:latest

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: package
        caches:
          - maven # adds docker layer caching
          - node
        script:
          - echo $PATH
          - ls -latr /apps/maven/bin
          - export PATH=/apps/maven/bin:${PATH}
          - export PATH=/usr/lib/node_modules/yarn/bin:${PATH}
          - echo $PATH
          - which mvn
          - which yarn
          - which node
          - mvn -version
          - yarn --version
          - npm --version
  branches:
   
    #SWU main branch
    develop-v2:
      - step:
          name: package
          caches:
            - maven # adds docker layer caching
            - node
            - git-modules
          script:
            - git checkout develop-v2
            - git reset --hard "origin/develop-v2"
            - git submodule sync
            - git submodule update --remote --init && echo "OK - git submodule update --remote --init"
            - git submodule foreach "git lfs pull"
            - mvn clean package -DskipTests=true -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          artifacts:
            - swinburne-core-deploy/target/*.zip
            - swinburne-core-testing/target/**

      #- step:
      #    name: install to dev
      #    trigger: manual
      #    deployment: test
      #    script:
      #      - echo "Disabled deployment"
           # - mvn -Dvault.useProxy=false -DskipTests -e -U -P deploymentpackage,installdeploymentpackage clean install -Dcrx.host=$DEV_AUTHOR_HOST -Dcrx.port=$DEV_AUTHOR_PORT -Dcrx.username=$DEV_AUTHOR_USER -Dcrx.password=$DEV_AUTHOR_USER_PASSWORD -e -U -P deploymentpackage,installdeploymentpackage -DskipTests=true -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
           # - mvn -Dvault.useProxy=false -DskipTests -e -U -P deploymentpackage,installdeploymentpackage clean install -Dcrx.host=$DEV_PUBLISH1_HOST -Dcrx.port=$DEV_PUBLISH1_PORT -Dcrx.username=$DEV_PUBLISH1_USER -Dcrx.password=$DEV_PUBLISH1_USER_PASSWORD -e -U -P deploymentpackage,installdeploymentpackage -DskipTests=true -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn




definitions:
  services:
    docker:
      memory: 2048
  caches:
    git-modules: .git/modules
