# Modifiers
content/cq:tags/swinburne/component-style-modifier: &component-style-modifier

# Themes
content/cq:tags/swinburne/component-style-theme: &component-style-theme

  #styleguide
  styleguide/rohan:
    flat: true
    prefix: 'theme--rohan-2'
    title: 'Rohan Test panel'

  styleguide/rohan-test-2:
    flat: true
    prefix: 'theme--rohan-test-2'
    title: 'Rohan Test 222 '

  styleguide/rohan-test-3:
    flat: true
    prefix: 'theme--rohan-test-3'
    title: 'Rohan Test 4444 '

# Modules
content/cq:tags/swinburne/component-style-module: &component-style-module

# Icon
content/cq:tags/swinburne/component-style-icon: &component-style-icon

# Analytics
content/cq:tags/swinburne/component-analytics: &component-analytics

# Chevron
content/cq:tags/swinburne/component-style-chevron: &component-style-chevron

# Aria
content/cq:tags/swinburne/component-aria: &component-aria

# Dialog
content/cq:tags/swinburne/component-dialog: &component-dialog

content/cq:tags/swinburne/content-type: &content-type

content/cq:tags/swinburne/component-topic: &component-topic

content/cq:tags/swinburne-showcase/component-style-modifier: *component-style-modifier
content/cq:tags/swinburne-showcase/component-style-module: *component-style-module
content/cq:tags/swinburne-showcase/component-style-theme: *component-style-theme
content/cq:tags/swinburne-showcase/component-style-icon: *component-style-icon
content/cq:tags/swinburne-showcase/component-style-chevron: *component-style-chevron
content/cq:tags/swinburne-showcase/component-analytics: *component-analytics
content/cq:tags/swinburne-showcase/component-aria: *component-aria
content/cq:tags/swinburne-showcase/component-dialog: *component-dialog
content/cq:tags/swinburne-showcase/content-type: *content-type
content/cq:tags/swinburne-showcase/component-topic: *component-topic

content/cq:tags/swinburne-training/component-style-modifier: *component-style-modifier
content/cq:tags/swinburne-training/component-style-module: *component-style-module
content/cq:tags/swinburne-training/component-style-theme: *component-style-theme
content/cq:tags/swinburne-training/component-style-icon: *component-style-icon
content/cq:tags/swinburne-training/component-style-chevron: *component-style-chevron
content/cq:tags/swinburne-training/component-analytics: *component-analytics
content/cq:tags/swinburne-training/component-aria: *component-aria
content/cq:tags/swinburne-training/component-dialog: *component-dialog
content/cq:tags/swinburne-training/content-type: *content-type
content/cq:tags/swinburne-training/component-topic: *component-topic
