#!/bin/bash

# Check if Sync directory exists
if [ ! -d "sync/" ]; then
  echo Directory sync/ not found, run \"npm run aem:checkout\"vi a
  exit
fi

# TODO: Remove this and extract folder name from POM file
CLIENT_LIBS_FOLDER="swinburne"

echo Copying files from public to sync
cp -r public/ sync/jcr_root/etc/clientlibs/${CLIENT_LIBS_FOLDER}

echo Launching VLT
cd sync && ../tools/vault-cli/bin/vlt --verbose --credentials admin:admin ci --force  ./jcr_root/etc/clientlibs/${CLIENT_LIBS_FOLDER}
