#!/bin/bash

# Check if Sync directory exists
if [ ! -d "sync/" ]; then
  echo Directory sync/ not found, run \"npm run aem:checkout\"vi a
  exit
fi

CLIENT_LIBS_FOLDER=$(cat pom.xml | sed -n 's:.*<package\.clientLibsFolder>\(.*\)</package\.clientLibsFolder>.*:\1:p')

echo Copying files from public to sync
cp -r public/ sync/jcr_root/etc/clientlibs/${CLIENT_LIBS_FOLDER}

echo Launching VLT
cd sync && ../tools/vault-cli/bin/vlt --verbose --credentials admin:admin commit --force ./jcr_root/etc/clientlibs/${CLIENT_LIBS_FOLDER}
