#!/bin/bash

function set_term_title() {
   echo -en "\033]0;$1\a"
}

set_term_title "Creating Package: mvn -Dvault.useProxy=false -DskipTests clean package"

mvn -Dvault.useProxy=false -DskipTests clean package

set_term_title "Created"

