content/_cq_tags/swinburne-microsites/component-style-chevron: &component-style-chevron
  chevron:
    prefixes:
      - circle-down
      - circle-up
      - circle-right
      - circle-left
      - down
      - up
      - right
      - left
    valueFormat: fa fa-chevron-%%prefix%%
    title: '%%prefix_normalised%%'

# Extends to
content/_cq_tags/swinburne-microsites-showcase/component-style-chevron: *component-style-chevron
content/_cq_tags/swinburne-microsites-training/component-style-chevron: *component-style-chevron
