#!/bin/bash

POM_FILE="../pom.xml"
SCRIPT_PARAMS="$@"

source "../scripts/functions.sh"

echo selenium-grid-network: $(docker network create selenium-grid)

echo selenium-hub: $(docker run --rm -d -p $SELENIUMHUB_PORT:4444 --net selenium-grid --name selenium-hub -e GRID_TIMEOUT=10 selenium/hub)

echo selenium-hub-node-chrome: $(docker run --rm -d --net selenium-grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm --name selenium-hub-node-chrome selenium/node-chrome)
#echo selenium-hub-node-firefox: $(docker run --rm -d --net selenium-grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm --name selenium-hub-node-firefox selenium/node-firefox)
