#!/bin/bash

POM_FILE="../pom.xml"
SCRIPT_PARAMS="$@"

SKIP_PRINT_CONFIG=true

source "../scripts/functions.sh"

LOCAL_IP="$(ifconfig | grep 'inet ' | head -1 | grep -v '127.0.0.1' | awk '{print $2}' | head -1)"

EXEC_HOST="${1:-$LOCAL_IP}"
EXEC_ENV="${2:-local-chrome}" #localremote - seleniumhub - local-phantomjs
HUB_URL="${3:-$SELENIUMHUB_SCHEME://$LOCAL_IP:$SELENIUMHUB_PORT$SELENIUMHUB_SERVICE}"

./test-spec $EXEC_HOST $EXEC_ENV $HUB_URL