#!/bin/bash

POM_FILE="../pom.xml"
SCRIPT_PARAMS="$@"

SKIP_PRINT_CONFIG=true

source "../scripts/functions.sh"

LOCAL_IP="$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}')"

EXEC_HOST="${1:-$LOCAL_IP}"
HUB_URL="$SELENIUMHUB_SCHEME://$LOCAL_IP:$SELENIUMHUB_PORT$SELENIUMHUB_SERVICE"

./test-spec-seleniumhub $EXEC_HOST $HUB_URL
