#!/bin/bash

POM_FILE="../pom.xml"
SCRIPT_PARAMS="$@"

SKIP_PRINT_CONFIG=true

source "../scripts/functions.sh"

LOCAL_IP="$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -1)"

EXEC_AEM_HOST="${1:-$LOCAL_IP}"
EXEC_AEM_PORT="4502"

HUB_URL="$SELENIUMHUB_SCHEME://$LOCAL_IP:$SELENIUMHUB_PORT$SELENIUMHUB_SERVICE"

EXEC_TEST="*DLSPageListPublishSpec"

./test-spec-seleniumhub $EXEC_AEM_HOST $EXEC_AEM_PORT $HUB_URL $EXEC_TEST
