content/cq:tags/swinburne/component-style-icon: &component-style-icon
  feed/rss:
    flat: true
    prefix: 'fa fa-rss'
    title: 'RSS'
  feed/atom:
    flat: true
    prefix: 'fa fa-rss'
    title: 'Atom'

  social:
    prefixes:
      - youtube
      - facebook-f
      - pinterest-p
      - twitter
      - instagram
      - linkedin-in
    valueFormat: fa fa-%%prefix%%
    title: '%%prefix_normalised%%'

  spinner:
    prefixes:
      - cog
      - gear
      - refresh
      - spinner
    valueFormat: fa fa-%%prefix%%
    title: '%%prefix_normalised%%'

  general:
    prefixes:
      - fast-forward
      - comments
      - briefcase
      - calendar
      - search
      - home
      - edit
      - phone
      - pencil-alt
      - book
      - reply-all
      - life-ring
      - calculator
      - calendar-alt
      - envelope
      - star
      - car
      - street-view
      - globe
      - train
      - play-circle
      - user
      - users
      - users-class
      - user-graduate
      - balance-scale
      - building
      - chalkboard-teacher
      - child
      - comment-alt-exclamation
      - comment-alt-smile
      - comment-alt-check
      - comment-alt-dots
      - comments-alt
      - info-circle
      - laptop
      - location-circle
      - map-pin
      - plane-arrival
      - plane-departure
      - thumbs-up
      - thumbs-down
      - trophy
      - wheelchair
      - star
      - school
      - paper-plane
      - connectdevelop
      - graduation-cap
      - video
      - university
      - bar-chart
      - newspaper
      - cogs
      - gamepad
      - code
      - gavel
      - stethoscope
      - flask
      - wrench
      - heartbeat
      - link
    valueFormat: fa fa-%%prefix%%
    title: '%%prefix_normalised%%'

# Extends to
content/cq:tags/swinburne-showcase/component-style-icon: *component-style-icon
content/cq:tags/swinburne-training/component-style-icon: *component-style-icon
