content/cq:tags/swinburne/component-style-icon: &component-style-icon
  feed/atom:
    flat: true
    prefix: 'fa fa-rss'
    title: 'Atom'

  feed/rss:
    flat: true
    prefix: 'fa fa-rss'
    title: 'RSS'

  social:
    prefixes:
      - facebook
      - facebook-f
      - instagram
      - linkedin
      - linkedin-in
      - pinterest-p
      - tumblr
      - tumblr-square
      - twitter
      - youtube
    valueFormat: fab fa-%%prefix%%
    title: '%%prefix_normalised%%'

  spinner:
    prefixes:
      - cog
      - spinner
    valueFormat: fa fa-%%prefix%%
    title: '%%prefix_normalised%%'

  general:
    prefixes:
      - balance-scale
      - book
      - briefcase
      - building
      - calculator
      - calendar
      - calendar-alt
      - car
      - chalkboard-teacher
      - chart-bar
      - child
      - code
      - cogs
      - comment-alt-check
      - comment-alt-dots
      - comment-alt-exclamation
      - comment-alt-smile
      - comments
      - comments-alt
      - connectdevelop
      - edit
      - envelope
      - fast-forward
      - flask
      - gamepad
      - gavel
      - globe
      - graduation-cap
      - heartbeat
      - home
      - info-circle
      - laptop
      - life-ring
      - link
      - location-circle
      - map-pin
      - newspaper
      - paper-plane
      - pencil-alt
      - phone
      - plane-arrival
      - plane-departure
      - play-circle
      - reply-all
      - school
      - search
      - star
      - star
      - stethoscope
      - street-view
      - thumbs-down
      - thumbs-up
      - train
      - trophy
      - university
      - user
      - user-graduate
      - users
      - users-class
      - video
      - wheelchair
      - wrench
    valueFormat: fal fa-%%prefix%%
    title: '%%prefix_normalised%%'

# Extends to
content/cq:tags/swinburne-showcase/component-style-icon: *component-style-icon
content/cq:tags/swinburne-training/component-style-icon: *component-style-icon
