content/cq:tags/swinburne/component-style-modifier: &component-style-modifier
  # Backgrounds
  background:
    prefixes:
      - blue
      - blue-50
      - dark
      - green
      - green-50
      - grey-1
      - grey-2
      - grey-3
      - grey-4
      - grey-5
      - purple
      - purple-50
      - red
      - red-50
      - tertiary
      - turquoise
      - turquoise-50
      - yellow
      - yellow-50
    startWith: bg-
    title: 'Background Colour - %%prefix_normalised%%'

  background/standard:
    prefixes:
      - danger
      - dark
      - faded
      - info
      - inverse
      - light
      - primary
      - success
      - warning
    valueFormat: bg-%%prefix%%
    title: '%%prefix_normalised%%'

  border:
    sizes:
      - '0'
      - '1'
    prefixes:
      - border
      - border-bottom
      - border-top
      - border-left
      - border-right
      - rounded
      - rounded-bottom
      - rounded-top
      - rounded-left
      - rounded-right
    title: '%%prefix_normalised%% %%size%%px'

  border/rounded-circle:
    flat: true
    prefix: rounded-circle
    title: 'Rounded Circle'

  # Content Inverted
  content/inverted:
    flat: true
    prefix: inverted
    title: 'Inverted'

  # Colours
  color:
    prefixes:
      - blue
      - blue-50
      - charcoal
      - green
      - green-50
      - grey-1
      - grey-2
      - grey-3
      - grey-4
      - grey-5
      - purple
      - purple-50
      - red
      - red-50
      - turquoise
      - turquoise-50
      - yellow
      - yellow-50
    startWith: text-
    title: 'Text Colour - %%prefix_normalised%%'

  # Colors Standard
  color/standard:
    prefixes:
      - black
      - danger
      - info
      - muted
      - primary
      - red
      - success
      - warning
      - white
    valueFormat: text-%%prefix%%
    title: '%%prefix_normalised%%'

  # Columns
  column/standard:
    prefixes:
      - xs
      - sm
      - md
      - lg
      - xl
    sizes:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    valueFormat: col-%%prefix%%-%%size%%
    title: 'Col %%prefix_normalised%% %%size%%'

  column/prefix-only:
    prefixes:
      - xs
      - sm
      - md
      - lg
      - xl
    valueFormat: col-%%prefix%%
    title: 'Col %%prefix_normalised%%'

  column/col:
    flat: true
    prefix: col
    title: 'Col'

  # Button
  button/group/group/vertical:
    flat: true
    prefix: btn btn-group-vertical
    title: 'Vertical'

  button/group/size/large:
    flat: true
    prefix: btn btn-group-lg
    title: 'Large'

  button/group/size/small:
    flat: true
    prefix: btn btn-group-sm
    title: 'Small'

  button/group/toolbar:
    flat: true
    prefix: btn btn-toolbar
    title: 'Toolbar'

  ## Button Normal
  button/normal:
    prefixes:
      - link
      - primary-red
      - primary-yellow
      - secondary-charcoal
      - secondary-outline
      - secondary-white
    valueFormat: btn btn-%%prefix%%
    title: '%%prefix_normalised%%'

  ## Button Outline
  button/outline:
    prefixes:
      - primary-red
      - primary-yellow
      - secondary-charcoal
      - secondary-outline
      - secondary-white
    valueFormat: btn btn-outline-%%prefix%%
    title: '%%prefix_normalised%%'

  ## Button Size
  button/size/block:
    flat: true
    prefix: btn btn-block
    title: 'Block (Full Width)'

  button/size/large:
    flat: true
    prefix: btn btn-lg
    title: 'Large'

  button/size/small:
    flat: true
    prefix: btn btn-sm
    title: 'Small'

  ## Button State
  button/state/active:
    flat: true
    prefix: active
    title: 'Active'

  button/state/disabled:
    flat: true
    prefix: disabled
    title: 'Disabled'

  # Cards
  card:
    prefixes:
      - promoted
    valueFormat: card--%%prefix%%
    title: 'Card - %%prefix_normalised%%'

  card/container:
    prefixes:
      - columns
      - deck
      - group
    valueFormat: card-%%prefix%%
    title: 'Card - %%prefix_normalised%%'

  card/background:
    prefixes:
      - danger
      - info
      - primary
      - success
      - warning
    valueFormat: card-%%prefix%%
    title: 'Background - %%prefix_normalised%%'

  card/outline:
    prefixes:
      - danger
      - info
      - primary
      - success
      - warning
    valueFormat: card-outline-%%prefix%%
    title: 'Outline - %%prefix_normalised%%'

  cards/direction:
    prefix: cards-horizontal
    title: 'Horizontal'

  # Content Block
  contentblock/banner/image:
    flat: true
    prefix: image-only
    title: 'Image Only'

  # Embed
  embed/default:
    flat: true
    prefix: embed-responsive embed-responsive-1by1
    title: 'Default'

  embed/embed-responsive-1by1:
    flat: true
    prefix: embed-responsive embed-responsive-1by1
    title: 'Responsive 1 by 1'

  embed/embed-responsive-4by3:
    flat: true
    prefix: embed-responsive embed-responsive-4by3
    title: 'Responsive 4 by 3'

  embed/embed-responsive-16by9:
    flat: true
    prefix: embed-responsive embed-responsive-16by9
    title: 'Responsive 16 by 9'

  embed/embed-responsive-21by9:
    flat: true
    prefix: embed-responsive embed-responsive-21by9
    title: 'Responsive 21 by 9'

  # Flexbox
  flex/align-items:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - baseline
      - center
      - end
      - start
      - stretch
    valueFormat: 'align-items%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  flex/align-self:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - baseline
      - center
      - end
      - start
      - stretch
    valueFormat: 'align-self%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  flex/direction:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - row
      - row-reverse
      - column
      - column-reverse
    valueFormat: 'flex%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  flex/justify-content:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - around
      - between
      - center
      - end
      - start
    valueFormat: 'justify-content%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  flex/order:
    breakpoints:
      - sm
      - md
      - lg
    sizes:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    prefix: order
    title: '%%sizeWithSuffix%% %%breakpoint%%'

  flex/wrap:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - nowrap
      - wrap
      - wrap-reverse
    valueFormat: 'flex%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  # Font
  font/font-weight-light:
    flat: true
    prefix: fw-300
    title: 'Font Weight (Light)'

  font/font-weight-normal:
    flat: true
    prefix: fw-400
    title: 'Font Weight (Normal)'

  font/font-weight-bold:
    flat: true
    prefix: fw-600
    title: 'Font Weight (Bold)'

  font/font-weight-bolder:
    flat: true
    prefix: fw-700
    title: 'Font Weight (Bolder)'

  # Grid
  grid/container:
    flat: true
    prefix: container
    title: 'Container'

  grid/container-flush:
    flat: true
    prefix: container-flush
    title: 'Container Flush'

  grid/container-width/container-sm:
    flat: true
    prefix: container-sm
    title: 'Container Small ( max 320px )'

  grid/container-width/container-md:
    flat: true
    prefix: container-md
    title: 'Container Medium ( max 640px )'

  grid/container-width/container-lg:
    flat: true
    prefix: container-lg
    title: 'Container Large ( max 1024px )'

  grid/container-width/container-xl:
    flat: true
    prefix: container-xl
    title: 'Container X Large ( max 1366px )'

  grid/list/pagelist/columns/column-1:
    flat: true
    prefix: column-1
    title: 'Column 1'

  grid/list/pagelist/columns/column-2:
    flat: true
    prefix: column-2
    title: 'Column 2'

  grid/list/pagelist/columns/column-3:
    flat: true
    prefix: column-3
    title: 'Column 3'

  grid/list/pagelist/columns/column-6:
    flat: true
    prefix: column-6
    title: 'Column 6'

  grid/list/pagelist/slides/slide-1:
    flat: true
    prefix: slide-1
    title: 'Slide 1'

  grid/list/eventlist/visibility/hidden:
    flat: true
    prefix: hidden
    title: 'hidden'

  # Icons
  icon/animation:
    prefixes:
      - pulse
      - spin
    prefixValue: fa-
    title: '%%prefix_normalised%%'

  icon/flip:
    prefixes:
      - horizontal
      - vertical
    prefixValue: fa-flip-
    title: '%%prefix_normalised%%'

  icon/size:
    prefixes:
      - xs
      - sm
      - md
      - lg
    prefixValue: icon--
    title: 'Icon Size (%%prefix_normalised%%)'

  icon/position:
    prefixes:
      - pull-left
      - pull-right
    prefixValue: fa-
    title: '%%prefix_normalised%%'

  icon/rotate:
    prefixes:
      - rotate-90
      - rotate-180
      - rotate-270
    prefixValue: fa-
    title: '%%prefix_normalised%%'

  # Images
  image/responsive:
    flat: true
    prefix: img-fluid
    title: 'Img Fluid'

  image/alignment:
    flat: true
    prefix: img-center
    title: 'Img Center'

  image/metadata:
    flat: true
    prefix: img-data-visible
    title: 'Img Data Visible'

  image/spacing:
    prefixes:
      - no-margin
      - no-padding
    valueFormat: img-%%prefix%%
    title: '%%prefix_normalised%%'

  # Margin
  margin:
    breakpoints:
      - sm
      - md
    emptyTitle: true
    prefixes:
      - m
      - mb
      - mt
      - ml
      - mr
      - mx
      - my
    sizes:
      - 0
      - 5
      - 10
      - 15
      - 20
      - 25
      - 30
      - 35
      - 40
    title: '%%prefix_normalised%% - %%size%%px %%breakpoint%%'

  margin/mx-auto:
    flat: true
    prefix: mx-auto
    title: 'Center Horizontally'

  # Padding
  padding:
    breakpoints:
      - sm
      - md
    emptyTitle: true
    prefixes:
      - p
      - pb
      - pt
      - pl
      - pr
      - px
      - py
    sizes:
      - 0
      - 5
      - 10
      - 15
      - 20
      - 25
      - 30
      - 35
      - 40
    title: '%%prefix_normalised%% %%size%%px %%breakpoint%%'

  # Text (Misc)
  text/list/colors:
    prefixes:
      - list-dark
    prefixValue: text-
    title: ' %%prefix_normalised%%'

  text/headings/style:
    prefixes:
      - heading-outlined
    prefixValue: text-
    title: 'No Underline'

  text/style:
    prefixes:
      - -underlined
    prefixValue: text-
    title: 'Underlined'

  # Text Alignments
  text/alignment:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - center
      - left
      - right
    prefixValue: text-
    title: 'Text Alignment (%%prefix_normalised%%) %%breakpoint%%'

  # Text transforms
  text/transform:
    prefixes:
      - capitalize
      - lowercase
      - none
      - uppercase
      - small
    prefixValue: text-
    title: 'Text Transform (%%prefix_normalised%%)'

  video:
    prefixes:
      - allowfullscreen
      - loop
      - mozAllowFullScreen
      - muted
      - playsinline
      - webkitallowfullscreen
    title: '%%prefix_normalised%%'

  visibility:
    prefixes:
      - invisible
      - invisible-lg-down
      - invisible-lg-up
      - invisible-md-down
      - invisible-md-up
      - invisible-sm-down
      - invisible-sm-up
      - invisible-xl-down
      - invisible-xl-up
      - invisible-xs-down
      - invisible-xs-up
      - sr-only
      - sr-only-focusable
      - text-hide
    title: '%%prefix_normalised%%'

# Extends to
content/cq:tags/swinburne-showcase/component-style-modifier: *component-style-modifier
content/cq:tags/swinburne-training/component-style-modifier: *component-style-modifier
